[tools]
node = "20"
python = "3.12"
aws-cli = "latest"

[env]
PROJECT_NAME = "{{ config_root | basename }}"
_.python.venv = { path = ".venv", create = true }

[tasks.info]
description = "Display project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''

# Documentation-related tasks
[tasks."docs:install"]
description = "Install documentation dependencies"
alias = "i"
run = "pip install -r requirements.txt"

[tasks."docs:build"]
description = "Build documentation"
run = "mkdocs build"

[tasks."docs:serve"]
description = "Serve documentation locally"
run = "mkdocs serve --dev-addr 0.0.0.0:8000"

[tasks."docs:deploy"]
description = "Deploy documentation to GitHub Pages"
run = "mkdocs gh-deploy"

[tasks.dev]
description = "Development workflow"
run = "docker-compose -f docker-compose.base.yml -f docker-compose.dev.yml up --build"

[tasks.test]
description = "Test workflow"
run = "docker-compose -f docker-compose.base.yml -f docker-compose.dev.yml --profile test up"